// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"ShowConsoleOnBoot","status":true,"description":"Shows the developer console on boot.","parameters":{"Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"MainText","status":true,"description":"","parameters":{}}
];
